### ISSUE TITLE
suggestion: use jsDelivr for CDN

### ISSUE THREAD

**Issue by tomByrer** [eggheadio-projects/the-beginner-s-guide-to-reactjs#12]
UNPKG is a good CDN which uses CloudFlare's solid CDN.  [jsDelivr](https://www.jsdelivr.com) uses CloudFlare also, plus fastly & StackPath CDNs, QUANTIL 600 POP CDN for China, loadbalanced by cedexis, 2 redundant DNS providers, & S3 file backup, engineered by an ex MaxCDN engineer. It can pull files from both NPM & Github. ([infographic](https://www.jsdelivr.com/network/infographic)).   Some online code editors like webpackbin and codesandbox use jsDelivr.

It also can [serve multiple files in one request](https://github.com/jsdelivr/jsdelivr#combine-multiple-files), eg:
`https://cdn.jsdelivr.net/combine/npm/react@16.2/umd/react.development.min.js,npm/react-dom@16.2/umd/react-dom.development.min.js,npm/@babel/standalone@7.0.0-beta.34`
After a few requests the collated file is cached at the POP, making subsequent requests faster.  Also helps with gzip total size.
test: http://jsbin.com/fucobut/edit?html,output

As I go though the videos, I'll update my fork.  Perhaps a PR changing the code wouldn't be a good idea, since the code is enshrined in the video, but perhaps consider for future revisions or videos?

Maybe I should do a video on jsDelivr?

**Comment by kentcdodds** [comment]
Thanks for the issue, but I'm not going to re-record all of the videos for this change and want the code to be consistent with the videos.

Thanks anyway :)
